@base_url = http://localhost:3000


### Status check

GET {{base_url}} HTTP/1.1



### post request on root

POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "name": "First User",
  "age": 20
}
