@base_url = http://localhost:3000


### Get the status

GET {{base_url}} HTTP/1.1



### Create task

POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "title": "hello"
}

### Create task - should fail because title is number

POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "title": 1
}

### Create task - should fail because title is empty

POST {{base_url}} HTTP/1.1
Content-Type: application/json

{
  "title": ""
}
